### ISSUE TITLE
Mod cards don't support ctrl-click or open in new tab

### ISSUE THREAD

**Issue by CDFN** [satisfactorymodding/smr-frontend#44]
Clicking RMB on mod's icon and then clicking "Open in new tab" results in **_image_** being opened in new tab instead mod's page (see picture).
I think it should open mod page as it does when we RMB outside the icon. It's very frustrating when collecting interesting mods for further research.
![image](https://user-images.githubusercontent.com/41289688/157754815-fc8ad724-8b75-4806-b923-4ead7298cdeb.png)

**Comment by budak7273** [comment]
This is how web browser images work - you're clicking 'open image in new tab'. That should open the image in the new tab.

It might be possible to attach another form of link to the image so that "open link in new tab" becomes an option as well.

In the mean time, you can ctrl-click or rightclick-'open link in new tab' on the mod's title text to open additional tabs.
